#!/bin/bash

function usage() {
    echo "usage: $0 <api-servers> [scale-servers]"
    echo "Both <api-servers> and <scale-servers> should be comma-separated lists of hsots."
    echo "To specify an authentication key, set the environment variable PANCAKE_AUTH_KEY."
    echo "For example: PANCAKE_AUTH_KEY=example $0 <api-servers> <scale-servers>"
}

# Check commands.
if [ "$#" -ne "2" -a "$#" -ne "1" ]; then
    usage
    exit 1
fi

api_servers=$(echo $1 | tr ',' '\n')
scale_servers=$(echo $2 | tr ',' '\n')
api_server_spec=""
api_auth_spec=""

# Set the authentication header spec.
if [ "x$PANCAKE_AUTH_KEY" != "x" ]; then
    api_auth_spec="-H 'X-Auth-Key: $PANCAKE_AUTH_KEY'"
fi

# Construct the API server string.
for server in $api_servers; do
    if [ "$api_server_spec" == "" ]; then
        api_server_spec="'$server'"
    else
        api_server_spec="$api_server_spec,'$server'"
    fi
done

# Contact all the given servers, starting with the API servers.
for server in $api_servers $scale_servers; do
    echo "Setting up $server..."
    curl -X POST \
        -d "{ 'api_servers' : [$api_server_spec] }" \
        $api_auth_spec \
        http://$server:8080/gridcentric/pancake/api_servers
    sleep 1
done
