#!/bin/bash

### BEGIN INIT INFO
# Provides:          reactor
# Required-Start:    $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Reactor
# Description:       Reactor manager
### END INIT INFO

LOGFILE=/var/log/reactor-manager.log
PIDFILE=/var/run/reactor-manager.pid
EXEC=reactor-manager

# Source function library.
. /etc/rc.d/init.d/functions

# Source configuration file.
. /etc/reactor-manager

case "$1" in
start)
    daemon --pidfile $PIDFILE $EXEC --log $LOGFILE --pidfile $PIDFILE --safe
    echo "reactor-manager"
;;
stop)
    killproc -p $PIDFILE $EXEC
    echo "reactor-manager"
;;
status)
    status -p $PIDFILE $EXEC
;;
restart)
    $0 stop
    $0 start
;;
*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
