#!/usr/bin/env python

import sys
import httplib
import time
import socket

sys.path.append('/etc/gridcentric/common')
import common

# Post to a reactor URL if given.
data = common.parse_params()
if "reactor" in data and data["reactor"]:
    rest_time = 0.01 # Start at 10ms.

    while True:
        try:
            conn = httplib.HTTPConnection(data["reactor"])
            conn.request("POST", "/v1.0/register", "", {})
            resp = conn.getresponse()
            if resp.status == 200:
                break
        except socket.error:
            pass

        # If we were not successful, do an exponential backoff,
        # but keep retrying every minute until we are successful.
        time.sleep(rest_time)
        if rest_time < 60.0:
            rest_time = (rest_time * 1.5)
