#!/bin/bash

set -e

function service_start() {
    if initctl status reactor | grep process >/dev/null 2>&1; then
        service reactor restart 2>/dev/null || \
        service reactor start;
    else
        service reactor restart 2>/dev/null || true
    fi
}

case $1 in
    configure) service_start;;
    triggered) service_start;;
esac
