#!/bin/bash

# Remove the reactor password.
# This will prevent interactive logins unless this script is somehow
# disabled on first boot, we rely on key injection.
passwd -d reactor

# For whatever reason, the service doesn't work on the first start.
# It's still unclear why, but the VM ends up messing with the network
# configuration -- so we avoid the situation by rebooting.
reboot
